import { redirect } from "next/navigation";

import { getCurrentUser } from "@/lib/auth";
import LogoutButton from "@/components/logout-button";

export default async function DashboardPage() {
  const user = await getCurrentUser();

    if (!user) {
        redirect("/login");
          }

            return (
                <main className="min-h-screen bg-gray-50">
                      <header className="border-b bg-white">
                              <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
                                        <div>
                                                    <h1 className="text-xl font-bold text-slate-700">
                                                                  Helpdesk SaaS
                                                                              </h1>

                                                                                          <p className="text-sm text-gray-500">
                                                                                                        Welcome, {user.name}
                                                                                                                    </p>
                                                                                                                              </div>

                                                                                                                                        <LogoutButton />
                                                                                                                                                </div>
                                                                                                                                                      </header>

                                                                                                                                                            <div className="mx-auto max-w-6xl px-6 py-10">
                                                                                                                                                                    <div className="rounded-2xl border border-gray-200 bg-white p-8 shadow-sm">
                                                                                                                                                                              <h2 className="text-2xl font-bold text-slate-700">
                                                                                                                                                                                          Dashboard
                                                                                                                                                                                                    </h2>

                                                                                                                                                                                                              <div className="mt-6 grid gap-4 md:grid-cols-3">
                                                                                                                                                                                                                          <div className="rounded-xl bg-blue-50 p-5">
                                                                                                                                                                                                                                        <p className="text-sm text-gray-500">
                                                                                                                                                                                                                                                        Name
                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                    <p className="mt-1 font-semibold text-slate-700">
                                                                                                                                                                                                                                                                                                    {user.name}
                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                          <div className="rounded-xl bg-blue-50 p-5">
                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                        Email
                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-1 font-semibold text-slate-700">
                                                                                                                                                                                                                                                                                                                                                                                                                    {user.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="rounded-xl bg-blue-50 p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Role
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-1 font-semibold text-blue-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {user.role}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }